### ISSUE TITLE
[Dustbin] Error after the mod disable

### ISSUE THREAD

**Issue by starfi5h** [soarqin/DSP_Mods#1]
Dustbin 1.1.0 DSP 0.9.27.15033
Steps to reproduce:
1. Turn a stroage box into Dustbin
2. Fill stroage box to full
3. Save, disable the mod and load again
4. Error when sorters trying to insert

![error](https://user-images.githubusercontent.com/50672801/205518828-cc8c84bd-cf97-45dd-ae89-f3cceee21f00.png)

我觉得把StorageComponent.bans设为负数, 以此来判断是否为垃圾桶不太安全  
建议可以用[DSPModSave](https://dsp.thunderstore.io/package/CommonAPI/DSPModSave/)另外储存数据, 或着改用能和原版游戏相容的安全作法

**Comment by soarqin** [comment]
确实目前字段不足以保存状态，C#的bool字段虽然可以当byte用，但是要patch的地方就太多了，可以考虑DSPModSave。
另外我还少patch了拆除建筑的函数，导致有其他bug，也要一并修正。
另外原本还打算给CompressSave加DSPModSave的支持，后来想想算了，modsv一般都很小。
