### ISSUE TITLE
LabOpt速度不太对

### ISSUE THREAD

**Issue by xiyuecangxin** [soarqin/DSP_Mods#10]
不知道是不是和别的mod冲突，开了之后差不多20秒才能造一个红块

**Comment by starfi5h** [comment]
是不是开了AlterTickrate或SampleAndHoldSim?

**Comment by xiyuecangxin** [comment]
> 是不是同时使用了AlterTickrate或SampleAndHoldSim? 目前这些mod还没有和Labopt做适配, 所以可能造成研究站产量异常

明白了，是AlterTickrate，但是不开这个更卡。。

**Comment by starfi5h** [comment]
暂且在AlterTickrate 0.2.3版做了适配 (研究站的优化部分全部让给LabOpt, 避免冲突)
可以测试看看还有没有问题

**Comment by soarqin** [comment]
LabOpt因为缺乏维护已经标识为过期
