### ISSUE TITLE
UXAssist 1.0.6 无法 将其转换为战斗模式

### ISSUE THREAD

**Issue by hellotaeyeon0214** [soarqin/DSP_Mods#17]
UXAssist 1.0.6 在加载旧存档时 无法 将其转换为战斗模式
紀錄版本号: 0.10.28.20779

**Comment by soarqin** [comment]
选项默认是关闭的，需要在面板上打开才会生效

**Comment by hellotaeyeon0214** [comment]
> 選項預設是關閉的，需要在面板上開啟才會生效

有开启功能,旧纪录可以使用此功能
,但旧纪录黑雾版本之后又存档过的是无法使用此功能

**Comment by hellotaeyeon0214** [comment]
> 選項預設是關閉的，需要在面板上開啟才會生效

已经测过版本0.9.27.19999以下的记录档使用转换为战斗模式是可行的
版本0.10.28.20771含之后是无法使用, 希望转换为战斗模式功能可以改成不限旧版本可使用

![dxxxxxxxxx](https://github.com/soarqin/DSP_Mods/assets/83624607/a6ea1b65-0a12-4f99-90db-725c3439357f)
