### ISSUE TITLE
Planets over 256 give error when starting game

### ISSUE THREAD

**Issue by daiceman2** [soarqin/DSP_Mods#18]
Game will now generate universe with up to 1024 stars, however upon starting, errors begin when game loads
![image_2023-12-16_143426203](https://github.com/soarqin/DSP_Mods/assets/50529283/6009fc98-1168-4958-bd87-699d2ea9455e)

**Comment by soarqin** [comment]
Fixed in UniverseGenTweaks 1.2.4
