### ISSUE TITLE
dustbin储物箱垃圾桶图标与新版（0.10.28.20829）筛选器按钮重合

### ISSUE THREAD

**Issue by mei-iem** [soarqin/DSP_Mods#19]
![image](https://github.com/soarqin/DSP_Mods/assets/97957593/43963594-5fcb-4c3e-855c-fed825e570f8)
如图，两个按钮重叠了，现在的问题是没办法点到过滤器
感谢修复

**Comment by soarqin** [comment]
已在1.3.2中修复
