### ISSUE TITLE
Cannot open the panel

### ISSUE THREAD

**Issue by Talars** [soarqin/DSP_Mods#21]
Hello there,

i am having a hard time figuring out which key combination i need to press to open the control panel. Tried the one mentioned under usage but no success, using a German Keyboard Layout.

**Comment by soarqin** [comment]
you can open the panel by clicking the new entry on main menu, or the small button aside the minimap in game, then set your own shortcut key on the panl.

**Comment by Talars** [comment]
So i have done something wrong since i do not have these buttons or entries. 

https://imgur.com/a/Xk1XFXH

**Comment by soarqin** [comment]
![image](https://github.com/soarqin/DSP_Mods/assets/172610/6df26add-d821-4902-981f-f00657d57151)
![image](https://github.com/soarqin/DSP_Mods/assets/172610/7f244021-8c05-40fd-8eca-098cb4ea02f4)
The 2 places I've mentioned above.

**Comment by Talars** [comment]
![image](https://github.com/soarqin/DSP_Mods/assets/154227778/218434a3-988f-410a-b565-fcf627f07e8c)
Yeah nothing like this available gonna re install mod manager and the mods

**Comment by Talars** [comment]
Okay installing everything new fixed it. Thanks for the support. Great Work
