### ISSUE TITLE
NXAssist 的 手搓物品优化与 DeliverySlotsTweaks 冲突

### ISSUE THREAD

**Issue by shenjackyuanjie** [soarqin/DSP_Mods#22]
https://github.com/soarqin/DSP_Mods/tree/master/UXAssist

https://github.com/starfi5h/DSP_Mod/tree/master/DeliverySlotsTweaks

**Comment by shenjackyuanjie** [comment]
打开手搓物品优化之后
DeliverySlotsTweaks 的 从物流背包拿取物品功能失效

**Comment by soarqin** [comment]
这个部分的patch只修改了点加减号的逻辑，应该不会和DeliverySlotTweaks冲突，会不会是其他选项导致的？

**Comment by starfi5h** [comment]
我测试单独UXAssist手搓优化+DeliverySlotsTweaks没有出现冲突。
是否能提供使用的mod列表?

**Comment by shenjackyuanjie** [comment]
稍等一会（

**Comment by shenjackyuanjie** [comment]
https://dsp.thunderstore.io/package/blacksnipebiu/Auxilaryfunction/

似乎是与 辅助多功能 的问题（

**Comment by shenjackyuanjie** [comment]
很好，重装一遍之后就没事了（魔法
