### ISSUE TITLE
UniverseGenTweak

### ISSUE THREAD

**Issue by ji-xingling** [soarqin/DSP_Mods#23]
![image](https://github.com/soarqin/DSP_Mods/assets/53159534/56452af2-8fe2-4249-9b0d-cf9f3ff98edf)
请问可以将这三个参数保存到配置中或者存档中吗，现在每次打开游戏都需要修改这三个参数，不然存档里的星系位置就会出现变动

**Comment by soarqin** [comment]
之前想过存在存档里，但DSPModSave不支持前置读取数据(后置读取时宇宙星系数据已经生成完毕)，我得想想其他办法

**Comment by soarqin** [comment]
已在1.2.5中支持
