### ISSUE TITLE
MechaDronesTweaks not working?

### ISSUE THREAD

**Issue by Reizorar** [soarqin/DSP_Mods#32]
Hi, I noticed that the mod stopped working today. Do you think it's because they rolled out a new version? 0.10.29.21863 is the latest one. The other option is that I've somehow disabled it by accident and I can't figure out how to enable it again, if it can be enabled/disabled ingame at all. Thanks for your contribution of course, the slow game is not enjoyable to me whatsoever.

Kind Regards,

Reizorar

**Comment by mikeleins** [comment]
definitely not working currently

**Comment by soarqin** [comment]
game compatibility issues should be fixed in 1.1.3/1.1.4
