### ISSUE TITLE
Not working this morning after NebulaMultiplayerModApi update.

### ISSUE THREAD

**Issue by amezick** [soarqin/DSP_Mods#34]
I don't see the icon in signals and I don't see the checkbox in the tanks/boxes.
I updated NebulaMultiplayerModApi this morning to v2.0.0 this morning

**Comment by amezick** [comment]
I use r2modman.
From the logs: 
[Error  :   BepInEx] Error loading [Dustbin 1.3.2] : Could not resolve type with token 01000034 (from typeref, class/assembly NebulaAPI.IMultiplayerMod, NebulaAPI, Version=1.3.1.0, Culture=neutral, PublicKeyToken=null)

**Comment by veldthui** [comment]
Same here

**Comment by amezick** [comment]
This is now resolved.  Thank you!
