### ISSUE TITLE
启动新游戏和加载旧的存档都会报错

### ISSUE THREAD

**Issue by MatchX** [soarqin/DSP_Mods#44]
![2024-08-16_010124](https://github.com/user-attachments/assets/422a3d06-edae-4ec8-9026-b5eef0cdd902)
采用r2modman 只安装了这一个mod

**Comment by soarqin** [comment]
收到，我会尽快修复

**Comment by soarqin** [comment]
已在2.3.17修复

**Comment by MatchX** [comment]
大神太牛了 立马就修复了 大赞 非常感谢
