### ISSUE TITLE
UXAssist Icon on top of Starmap

### ISSUE THREAD

**Issue by mpnewall43** [soarqin/DSP_Mods#46]
The UXAssist Config button is showing up on top of the Starmap button in the low right corner.
![Screenshot 2024-09-09 125649](https://github.com/user-attachments/assets/d747473b-f5ad-4557-a334-e2f1f21c6ddf)

**Comment by soarqin** [comment]
Thanks for reporting, will move it to another position to avoid overlapping in next version
