### ISSUE TITLE
拖动建造电线杆的建造逻辑问题

### ISSUE THREAD

**Issue by kkjj116** [soarqin/DSP_Mods#47]
拖动建造的时候中间自动设置成无线输电塔？
能不能改成全用电力感应塔？
![QQ图片20240921233055](https://github.com/user-attachments/assets/69f97dbc-d7c6-47af-afd5-4f39e7e49fe0)

**Comment by hunzhici** [comment]
![打开功能](https://github.com/user-attachments/assets/e7effec5-d8cf-43f2-b205-bf976c788aa6)
可以关闭无线输电塔
