### ISSUE TITLE
白天夜间巡航速度和扭曲闪烁机甲 - Daylight at night cruise speed and warp blinking mech

### ISSUE THREAD

**Issue by brianmangan** [soarqin/DSP_Mods#48]
在最近的补丁中，当启用“夜间日光”时，星际飞行时机甲会闪烁。

闪烁太严重了，由于光敏性癫痫，我需要将其关闭。  

如果你能解决这个问题，我将不胜感激。

----

With the recent patch, when flying interstellar the mech blinks when the 'daylight at night' is enabled.

The flickering is so bad that I need to turn it off due to photosensitive epileptic.  

if you could fix this, I would appreciate it.

**Comment by soarqin** [comment]
1.2.4中已经修复
