### ISSUE TITLE
[UXAsist] Keybind toggle issue rebind

### ISSUE THREAD

**Issue by SGZ-Creations** [soarqin/DSP_Mods#49]
> Press Alt+`(BackQuote) to call up the config panel. You can change the shortcut on the panel.

Can't find the mentioned panel to change the mentioned keybind curios to ask of this is an issue with GB mod or GS mod if not would like to hear what the issues was. Still hope this can be fixed soon.

Norwegian keyboards has the backtick(backquote) as a dead character. Press Shift + the key left of the Backspace.
![image](https://github.com/user-attachments/assets/2c5b64b6-9b0c-49f6-9dd5-61469babf49a)

**Comment by starfi5h** [comment]
You can change the keybind in the game settings
![image](https://github.com/user-attachments/assets/f401a0c4-f438-45d1-9e3b-9e1a5c17c5d3)

**Comment by SGZ-Creations** [comment]
I will look tho i couldn't find that one. TY

**Comment by SGZ-Creations** [comment]
Thanks found the keybind.
