### ISSUE TITLE
[UXassist] 矿脉保护功能未能正常生效

### ISSUE THREAD

**Issue by Seniorious0** [soarqin/DSP_Mods#50]
#### 1 
KeepOilSpeed，config file里修改无效。在沙盒中测试了一下，好像限制值永远都是生效成1.0f。
#### 2 
KeepVeinAmount设置为0时，使用一段时间后会异常报错，不同存档时长试了几次都这样。这个好像不太好复现，但应该是矿脉点快采完的时候出错吧。
![屏幕截图 2024-09-22 093052](https://github.com/user-attachments/assets/0c6efe15-1337-414c-865a-56a601f68152)

游戏版本0.10.30.23430，uxassist版本v1.2.5，都是最新的。

麻烦大佬有空的时候看看能不能修一下，谢谢

**Comment by qq7995516** [comment]
我用着有正常生效.

**Comment by soarqin** [comment]
已确认有这个bug

**Comment by qq7995516** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
