### ISSUE TITLE
Inserters with LabOptimization issue

### ISSUE THREAD

**Issue by NocturnalScream** [soarqin/DSP_Mods#6]
This is not caused/directly related to the mod - however when trying to use inserters/sorters on the higher up labs, you will find that those can not be powered. This is due to the powerfield generated by power poles etc. is actually a sphere and not a cylinder. This also affects my vertical Assembler mod. Do you have a suggestion to fix this?

**Comment by soarqin** [comment]
Using blueprint to connect higher level labs is not a good idea here.
If you are trying to using LabOpt's function with this way, you will get some issue after disabling LabOpt (which is common if LatOpt is not updated to be compatbile with newer game versions).
If you are really going to use sorters on higher level labs, I suggest not to connect high levels and use `Satellite Substation` to supply power.

**Comment by soarqin** [comment]
LabOpt is obseleted due to lack of maintainance, closing this
