### ISSUE TITLE
PoolOpt优化未半而中道异常

### ISSUE THREAD

**Issue by newbienoobplayer** [soarqin/DSP_Mods#9]
![Screenshot (487)](https://github.com/soarqin/DSP_Mods/assets/138718840/f4159f64-c15d-4244-ba54-1c1405a5dfd5)
[LogOutput.log](https://github.com/soarqin/DSP_Mods/files/12504054/LogOutput.log)

**Comment by shenjackyuanjie** [comment]
优化未半而中道异常绷不住了（

**Comment by newbienoobplayer** [comment]
> 优化未半而中道异常绷不住了（

好歹证明了我是国人(

**Comment by shenjackyuanjie** [comment]
hhhhhh
那确实

**Comment by newbienoobplayer** [comment]
可信度很高对吧?，话说你会修报错吗？，能不能帮我修一修？

**Comment by shenjackyuanjie** [comment]
![image](https://github.com/soarqin/DSP_Mods/assets/54507071/c4cd54b9-8a29-460a-90ee-792f74d2baec)
 你可能需要先升级一下beplex
以及log里并没有实际上的报错

**Comment by newbienoobplayer** [comment]
我的beplex已经是最新版了好像

**Comment by newbienoobplayer** [comment]
而且我的意思是我有另外一个抱错的情况

**Comment by soarqin** [comment]
之前的问题已经在新版修正，请用最新版测试后确认问题依然存在

**Comment by newbienoobplayer** [comment]
好，我午夜再试试，谢谢

**Comment by newbienoobplayer** [comment]
成了,谢谢
